### ISSUE TITLE
cluster_name field not being shipped

### ISSUE THREAD

**Issue by jamiebuxxx** [ApsOps/filebeat-kubernetes#12]
Hello, I started using the container recently, its working great so far. However, its an env variable to add the cluster_name is your are running multiple clusters. However, I'm unable to see that field after shipping our logs through our logging pipeline. We are using shipping to `logstash 5.2.2`. This is not a big deal for us at the moment, but wanted to bring this to your attention.

**Comment by jamiebuxxx** [comment]
Ah, I see. The cluster name field is not built into the container. I will rebuild a new container and see if that helps.

**Comment by ApsOps** [comment]
Hi @jamiebuxxx . The `cluster_name` field is [present](https://github.com/ApsOps/filebeat-kubernetes/blob/e867833faa95bde551d70e0cd3249cd1ad116f24/filebeat.yml#L16) in the container.

Make sure you're using the latest release (v0.5 as of now).

Also, have you refreshed your index field list in Kibana? Otherwise the new fields may not show up.

**Comment by jamiebuxxx** [comment]
Yes, the new field showed up once we updated the container version. Btw, this is an awesome, great work!
