### ISSUE TITLE
Error in resolving LOGSTASH_HOSTS

### ISSUE THREAD

**Issue by spyrosg** [ApsOps/filebeat-kubernetes#3]
Hi

I get the following error when running the container:

`tcp.go:26: WARN DNS lookup failure "'logstash.foo": lookup 'logstash.foo: invalid domain name
 `

My yaml file looks like:

```yaml 
   - name: LOGSTASH_HOSTS
     value: "'logstash.foo:5959'" 
```

The container works correctly if I pass `logstash.foo:5959` in `filebeat.yml` e.g.

` hosts: ["logstash.foo:5959"]`

Any ideas?

**Comment by ApsOps** [comment]
@spyrosg Hey, are you building from master? If yes, remove all quotes from `LOGSTASH_HOSTS` variable value. This is in progress for upgrading to filebeat 5.x

You can use stable tagged release for using filebeat 1.2.x

**Comment by spyrosg** [comment]
Yes I was building from master. Removing the quotes fixed the issue.

I'm still getting some error messages though:

`sync.go:85: ERR Failed to publish events caused by: read tcp 100.96.2.44:45872->100.65.25.58:5959: i/o timeout` 

But messages do show up in Kibana.

**Comment by ApsOps** [comment]
@spyrosg That is a filebeat error log which is shown when it is unable to send logs - it retries after some time though.

Reason could be temporary network issue, or  logstash pipeline is blocked because of too many requests or slowdown. You may consider scaling your logstash if it is under heavy load.
